-- auto Generated on 2019-06-06
-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	email VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
	INDEX(id),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
