server:
  port: 4042
spring:
  application:
    name: cloud-gateway-eureka
  cloud:
    gateway:
     discovery:
        locator:
         enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3030/eureka/
logging:
  level:
    org.springframework.cloud.gateway: info